apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: k-s-demo-app--
build:
  artifacts:
    - image: rassidm/k8s-demo-app
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml